services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imperecta_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=200'

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --requirepass imperecta

volumes:
  postgres_data: