"""All ORM models for Alembic metadata discovery."""

from app.models.core import User, UserProduct, UserSubscription  # noqa: F401
from app.models.dimensions import (  # noqa: F401
    DimBrand,
    DimCategory,
    DimCountry,
    DimCurrency,
    DimDate,
    DimMarketplace,
    DimProduct,
    DimSeller,
)
from app.models.facts import (  # noqa: F401
    FactCommodityPrice,
    FactCryptoPrice,
    FactCurrencyRate,
    FactFuelPrice,
    FactListing,
    FactPrice,
    FactPromo,
    FactReview,
    FactSearchTrend,
    FactStock,
    FactTariff,
)
from app.models.app_tables import (  # noqa: F401
    AIChatMessage,
    AIChatSession,
    Alert,
    AlertEvent,
    ApiLog,
    DataExport,
    Digest,
    ScrapeJob,
    ScrapeLog,
)

__all__ = [
    "User",
    "UserSubscription",
    "UserProduct",
    "DimDate",
    "DimCountry",
    "DimCurrency",
    "DimMarketplace",
    "DimCategory",
    "DimBrand",
    "DimProduct",
    "DimSeller",
    "FactListing",
    "FactPrice",
    "FactReview",
    "FactStock",
    "FactSearchTrend",
    "FactCurrencyRate",
    "FactTariff",
    "FactPromo",
    "FactCryptoPrice",
    "FactCommodityPrice",
    "FactFuelPrice",
    "Alert",
    "AlertEvent",
    "Digest",
    "AIChatSession",
    "AIChatMessage",
    "ScrapeJob",
    "ScrapeLog",
    "ApiLog",
    "DataExport",
]
