"""reject_data table + scrape_logs not_a_product status.

Revision ID: 024_reject_data_and_not_a_product
Revises: 023_scrape_logs_currency_rejected
Create Date: 2026-06-19
"""

from alembic import op

revision = "024_reject_data_and_not_a_product"
down_revision = "023_scrape_logs_currency_rejected"
branch_labels = None
depends_on = None

_STATUSES_WITH_NOT_A_PRODUCT = (
    "'success', 'no_change', 'error', 'timeout', 'blocked', 'captcha', "
    "'not_found', 'price_not_found', 'parse_error', 'currency_rejected', "
    "'not_a_product', 'missing_critical_data', 'technical_error', 'fetch_failed', "
    "'parse_failed', 'quota_exceeded', 'persist_failed'"
)

_STATUSES_WITHOUT_NOT_A_PRODUCT = (
    "'success', 'no_change', 'error', 'timeout', 'blocked', 'captcha', "
    "'not_found', 'price_not_found', 'parse_error', 'currency_rejected', "
    "'missing_critical_data', 'technical_error', 'fetch_failed', "
    "'parse_failed', 'quota_exceeded', 'persist_failed'"
)


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS reject_data (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            source VARCHAR(50) NOT NULL,
            table_target VARCHAR(50) NOT NULL,
            marketplace_id UUID NULL,
            listing_id UUID NULL,
            reject_reason VARCHAR(100) NOT NULL,
            failed_rules JSONB NULL,
            raw_payload JSONB NOT NULL,
            signature_present BOOLEAN NOT NULL DEFAULT false,
            rejected_by VARCHAR(20) NOT NULL
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_reject_data_created_at ON reject_data (created_at)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_reject_data_source ON reject_data (source)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_reject_data_reject_reason ON reject_data (reject_reason)"
    )

    op.execute("ALTER TABLE scrape_logs DROP CONSTRAINT IF EXISTS ck_scrape_logs_status")
    op.execute(
        "ALTER TABLE scrape_logs DROP CONSTRAINT IF EXISTS scrape_logs_status_check"
    )
    op.execute(
        "ALTER TABLE scrape_logs ADD CONSTRAINT ck_scrape_logs_status "
        f"CHECK (status IN ({_STATUSES_WITH_NOT_A_PRODUCT}))"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE scrape_logs DROP CONSTRAINT IF EXISTS ck_scrape_logs_status")
    op.execute(
        "ALTER TABLE scrape_logs DROP CONSTRAINT IF EXISTS scrape_logs_status_check"
    )
    op.execute(
        "ALTER TABLE scrape_logs ADD CONSTRAINT ck_scrape_logs_status "
        f"CHECK (status IN ({_STATUSES_WITHOUT_NOT_A_PRODUCT}))"
    )
    op.execute("DROP INDEX IF EXISTS idx_reject_data_reject_reason")
    op.execute("DROP INDEX IF EXISTS idx_reject_data_source")
    op.execute("DROP INDEX IF EXISTS idx_reject_data_created_at")
    op.execute("DROP TABLE IF EXISTS reject_data")
